AllCops:
  Exclude:
    - "bin/**/*"
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
