default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: reader_tracker_development
  host: localhost
  username: reader_tracker
  password: password

test:
  <<: *default
  database: reader_tracker_test
  host: localhost
  username: reader_tracker
  password: password

production:
  <<: *default
  database: reader_tracker_production
  username: reader_tracker_backend
  password: <%= ENV['READER_TRACKER_DATABASE_PASSWORD'] %>
